Ajout du drawer de création de comité
anct-cnum/suite-gestionnaire-numerique pull request #220
Opened 2024-11-29 11:11 UTC by Alezco

# Contrat du dev

## Qualité

- [ ] Relire le code
- [ ] Relire le ticket
- [ ] Recetter l'application
- [ ] Regarder le commentaire de sonarcloud et corriger s'il est pertinent
- [ ] Ajouter des variables d'environnement sur la production au besoin

## Accessibilité

- [ ] Vérifier l'accessibilité avec a11y.css
- [ ] Vérifier l'accessibilité avec WAVE
- [ ] Vérifier l'accessibilité avec Axe
- [ ] Vérifier l'accessibilité avec headingMap
- [ ] Vérifier le constraste en mode sombre

## Facultatif mais fortement conseillé

- [ ] Lancer les tests de mutation

> **Et n'oublie pas de vérifier ce que tu as fait en production !**

2024-12-02 08:04 UTC, NerOcrO commented
Je pense que ta PR est un très bon candidat pour commencer à utiliser :
- [<Form>](https://nextjs.org/blog/next-15#form-component)
- (mettre la notion de FormData dans la server action)[https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations] ce qui fait que l'on envoie du JS moins gros à l'utilisateur et j'imagine moins de test en front puisque ça sera géré en back donc on gagnera un peu de seconde (?)

2024-12-02 12:59 UTC, NerOcrO requested changes

2024-12-02 12:59 UTC, NerOcrO commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +]
à mettre vers le bas

2024-12-02 12:59 UTC, NerOcrO commented on src/components/Gouvernance/Comitologie/Comitologie.test.tsx
> +  it('quand je remplis entièrement le formulaire d’ajout de comitologie, le bouton de validation devient cliquable', () => {
Ce test ne correspond pas au ticket puisque la date et le commentaire sont optionnels

2024-12-02 13:12 UTC, Alezco commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +      </h1>
Pas possible ici parce que le composant aligne l'icône et le titre alors que sur la maquette, ils sont sur 2 lignes

2024-12-02 13:17 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +    console.log(type, frequence, date, commentaire)
À supprimer.

2024-12-02 13:17 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +  }
Le comportement de cette fonction n'est pas testé.

2024-12-02 13:17 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +    const isDisabled = [...form.values()].some((value) => value === '')
```suggestion
    const isDisabled = false
```

2024-12-02 13:17 UTC, meha-octo commented on src/components/shared/TextInput/TextInput.tsx
> +  min?: string
Cet attribut n'a pas les mêmes restrictions de [syntaxe suivant le type d'_input_](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/min#syntax). `string` est trop générique, rien n'empêcherait de passer pour valeur `foo` à un `input` de type `number`. Ne faudrait-il pas décliner ce composant en plusieurs sous-types ?

2024-12-02 13:25 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/Comitologie.test.tsx
> +    fireEvent.change(dateProchainComite, { target: { value: '2034-01-01' } })
```suggestion
    fireEvent.change(dateProchainComite, { target: { value: '1970-01-01' } })
```

2024-12-02 13:31 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +  const dateDuJour = new Date().toISOString().slice(0, 10)
Mettons qu'un utilisateur ouvre cette page un jour, et qu'il remplit le formulaire le lendemain : pourra t-il renseigner comme date du prochain comité, la date de la veille ?

2024-12-02 16:49 UTC, Alezco commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +    console.log(type, frequence, date, commentaire)
L'idée ici est de récupérer les variables qu'on enverra ensuite à la server action. Puisqu'on compte faire ça dans un 2ème ticket, je voulais juste créer un début de fonction qui servira pour plus tard

2024-12-02 17:33 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +  }
https://github.com/anct-cnum/suite-gestionnaire-numerique/pull/220#discussion_r1866295651
Ça permettrait de tester complètement ce code et de ne plus revenir dessus une fois la _server action_ implémentée.

2024-12-03 09:05 UTC, meha-octo commented on src/components/Gouvernance/Comitologie/ComitologieRemplie.tsx
> +            })
```suggestion
            comites.map(({nom, dateProchainComite, periodicite}) => (
              <tr key={nom}>
                <td>
                  <span
                    aria-hidden="true"
                    className="fr-icon-calendar-event-line color-blue-france"
                  />
                </td>
                <td className="font-weight-700">
                  {nom} : {dateProchainComite}
                </td>
                <td className="color-grey">
                  {periodicite}
                </td>
              </tr>
            ))
```

2024-12-03 09:25 UTC, Alezco commented
@meha-octo 

> Le rendu n'est pas fidèle à la maquette, sur le champ de date notamment, qui n'a pas la bonne largeur, ni le bon _placeholder_, ni le bon pictogramme. Aussi, le _drawer_ devrait se fermer une fois le bouton "enregistrer" cliqué.

- Pour la largeur du champ, je corrige
- Pour le placeholder, le navigateur "oblige" à utiliser le `jj/mm/aaaa` par défaut et il faut un peu [magouiller](https://stackoverflow.com/questions/20321202/not-showing-placeholder-for-input-type-date-field) pour mettre un autre placeholder. J'ai vu avec David, il est ok pour garder ce placeholder par défaut
- Pour le pictogramme, le DSFR utilise bien ce [design](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/champ-de-saisie). Vu aussi avec David, il est pour utiliser le design du DSFR plutôt que celui des maquettes
- Pour la fermeture du drawer, je comptais le faire une fois le branchement fait avec la server action, mais je m'occupe de le rajouter sur cette PR

2024-12-03 16:02 UTC, Alezco commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +  const dateDuJour = new Date().toISOString().slice(0, 10)
Le seul moyen que j'ai trouvé pour formatter en `jj-mm-aaaa` (format nécessaire aux `input type="date"`, c'est `new Intl.DateTimeFormat('en-CA').format(new Date())` (donc en format canadien). Qu'est-ce que tu préfères entre ça et `.slice(0, 10)` ?

2024-12-04 10:48 UTC, Alezco commented
@NerOcrO 

> Quand je navigue au clavier dans le drawer, il n'y a pas de focus sur les bouton radios alors qu'ils y sont bien dans le DSFR.

Je constate le même comportement sur cette PR et sur le DSFR : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/controle-segmente/

2024-12-05 09:29 UTC, Alezco commented on src/components/Gouvernance/Comitologie/AjouterUnComite.tsx
> +  }
:+1:

2024-12-05 10:14 UTC, NerOcrO approved these changes

2024-12-05 11:11 UTC, merged